
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_AXI_GPIO_CTRL_DEVICE_ID,
		XPAR_AXI_GPIO_CTRL_BASEADDR,
		XPAR_AXI_GPIO_CTRL_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_CTRL_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_KEY_VAL_DEVICE_ID,
		XPAR_AXI_GPIO_KEY_VAL_BASEADDR,
		XPAR_AXI_GPIO_KEY_VAL_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_KEY_VAL_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_STATUS_DEVICE_ID,
		XPAR_AXI_GPIO_STATUS_BASEADDR,
		XPAR_AXI_GPIO_STATUS_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_STATUS_IS_DUAL
	}
};


